Pushing 1.1.1d changes

diff --git a/scripts/dsym_upload b/scripts/dsym_upload
--- a/scripts/dsym_upload
+++ b/scripts/dsym_upload
@@ -8,16 +8,11 @@ eval "${GCC_PREPROCESSOR_DEFINITIONS}"
 
 SKIP_PROMPT=0
 UPLOAD_DSYM=0
-PROCESS_TYPE=1
+PROCESS_TYPE=0
+FAIL_ON_ERROR=0
 #Apple script alert before dSYM upload
 function error_prompt() {
-osascript <<EOT
-tell app "System Events"
-
-button returned of (display alert "$1" message "$2" buttons {"Ok"} default button 1 as critical giving up after 10)
-
-end tell
-EOT
+echo "$1: $2"
 }
 
 function prompt() {
@@ -31,8 +26,10 @@ EOT
 }
 
 exitOperation() {
-value=$(error_prompt "Error occured" "$1")
+value=$(error_prompt "Error" "$1")
+if [ $FAIL_ON_ERROR -eq 1 ]; then
 exit ${2}
+fi
 }
 
 AP_INFO_FILE_NAME="$PRODUCT_SETTINGS_PATH" #INFOPLIST_FILE
@@ -93,14 +90,17 @@ echo "ZA_INFOPLIST_FILE --- ${ZA_INFOPLIST_FILE}"
 
 while [ $# -gt 0 ]; do
 case "$1" in
---skip-prompt=*)
-SKIP_PROMPT=${1#*=}
+--skip-prompt)
+SKIP_PROMPT=1
 ;;
---process-type=*)
-PROCESS_TYPE=${1#*=}
+--process-in-background)
+PROCESS_TYPE=1
 ;;
---upload-dsym=*)
-UPLOAD_DSYM=${1#*=}
+--upload-dsym)
+UPLOAD_DSYM=1
+;;
+--fail-on-error)
+FAIL_ON_ERROR=1
 ;;
 *)
 printf "**********************************\n"
@@ -113,19 +113,20 @@ shift
 done
 
 if [ $UPLOAD_DSYM -eq 1 ]; then
-
-CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}")"
-while ([ ! -f "$CM_ZA_INFOPLIST_FILE" ])
+# We are searcing for the file excluding hidden dirs "-not -path '*/.*'"
+CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}" -not -path '*/.*' | head -1)"
+while ([ ! -f "${CM_ZA_INFOPLIST_FILE}" ])
 do
-  CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}")"
-echo "Waiting for the file to be copied ${CM_ZA_INFOPLIST_FILE}"
+  CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}" -not -path '*/.*' | head -1)"
+echo "Waiting for the file to be copied at line number 121 ${CM_ZA_INFOPLIST_FILE}"
 sleep 1;
 done
   
 echo $(/usr/libexec/PlistBuddy -c "Delete :APP_VERSION_META" "${ZA_INFOPLIST_FILE}")
 echo $(/usr/libexec/PlistBuddy -c "Delete :EVENTS_INFO" "${ZA_INFOPLIST_FILE}")
 echo $(/usr/libexec/PlistBuddy -c "Delete :API_INFO" "${ZA_INFOPLIST_FILE}")
-
+echo $(/usr/libexec/PlistBuddy -c "Delete :LAST_MODIFIED" "${ZA_INFOPLIST_FILE}")
+    
 echo $(/usr/libexec/PlistBuddy -c "Delete :AP_INFOPLIST_FILE" "${AP_INFO_FILE_NAME}")
 echo $(/usr/libexec/PlistBuddy -c "Delete :AP_APP_GROUP_IDENTIFIER" "${AP_INFO_FILE_NAME}")
 
@@ -139,7 +140,7 @@ API_KEY=$(/usr/libexec/PlistBuddy -c 'Print API_KEY' "${ZA_INFOPLIST_FILE}")
 fi
 
 if [ ! "${API_KEY}" ]; then
-value=$(error_prompt "Missing API_KEY" "Please check if the ${ZA_INFO_FILE_NAME} file is up to date?")
+value=$(error_prompt "Error" "Missing API_KEY, please check if the ${ZA_INFO_FILE_NAME} file is up to date?")
 exit 1
 fi
 
@@ -151,8 +152,8 @@ if [ "${SERVER_URL}" ]; then
 DSYM_UPLOAD_ENDPOINT="${SERVER_URL}/sdk/api/apptics/v1/adddsymfile"
 echo "SERVER_URL : ${SERVER_URL}"
 else
-value=$(error_prompt "Missing SERVER_URL in your ${ZA_INFO_FILE_NAME}" "Please if the file is up to date?" )
-exit 0
+value=$(error_prompt "Error" "Missing SERVER_URL in your ${ZA_INFO_FILE_NAME}, please if the file is up to date?" )
+exit 1
 fi
 
 echo "Uploading dSYM to Apptics server..."
@@ -223,7 +224,7 @@ if [ "$ENABLE_BITCODE" == "YES" ]; then
 AP_ENABLE_BITCODE="true"
 fi
 
-DSYM_UPLOAD_PARAMS="appv ersionid=${APP_VERSION_ID}&appreleaseversionid=${APP_RELEASE_VERSION_ID}&pid=${PLATFORM_ID}&apid=${APID}&isBitcodeenabled=${AP_ENABLE_BITCODE}&host=${WHOAMI}&remoteaddress=${IPADDRESS}"
+DSYM_UPLOAD_PARAMS="appversionid=${APP_VERSION_ID}&appreleaseversionid=${APP_RELEASE_VERSION_ID}&pid=${PLATFORM_ID}&apid=${APID}&isBitcodeenabled=${AP_ENABLE_BITCODE}&host=${WHOAMI}&remoteaddress=${IPADDRESS}"
 
 if [ "$EFFECTIVE_PLATFORM_NAME" == "-iphonesimulator" ]; then
 if [ "$UPLOAD_SIMULATOR_SYMBOLS" == "0" ]; then
@@ -269,7 +270,7 @@ if [ ${DEBUG_INFORMATION_FORMAT} == "dwarf-with-dsym" ]; then
     #move to tmp dir to make zip.
     cd /tmp/
 
-    (/usr/bin/zip -rv --quiet "${DSYM_ZIP_FPATH}.zip" "$AP_DWARF_DSYM_FILE_NAME") || exitOperation "error: failed creating zip" 0
+    (/usr/bin/zip -rv --quiet "${DSYM_ZIP_FPATH}.zip" "$AP_DWARF_DSYM_FILE_NAME") || exitOperation "Error: failed creating zip" 1
 
     echo "${DSYM_ZIP_FPATH}.zip"
     echo "Archive created."
@@ -280,32 +281,42 @@ if [ ${DEBUG_INFORMATION_FORMAT} == "dwarf-with-dsym" ]; then
     #come to the native dir.
     cd -
     #upload dsym through ruby script.
-    echo $(ruby -r "$(command dirname -- "${0}")/apptics_utils.rb" -e "AppticsUploader.main '${DSYM_ZIP_FPATH}.zip','${URL}?${DSYM_UPLOAD_PARAMS}','${API_KEY}'")
+    value=$(ruby -r "$(command dirname -- "${0}")/apptics_utils.rb" -e "AppticsUploader.main '${DSYM_ZIP_FPATH}.zip','${URL}?${DSYM_UPLOAD_PARAMS}','${API_KEY}'")
     # Remove dSYM archive from tmp dir
+    echo "$value"
+    
+    if [[ "$value" =~ ^Error:* ]]; then
+    if [ $FAIL_ON_ERROR -eq 1 ]; then
+        exit 1
+    fi
+    fi
+        
     echo "Cleaning up dSYM archive from temp dir..."
     /bin/rm -rv "${DSYM_ZIP_FPATH}.zip"
     /bin/rm -rv "${DSYM_ZIP_FPATH}"
 
     if [ "$?" -ne 0 ]; then
-    exitOperation "an error was encountered while uploading dSYM to the server" 0
+    exitOperation "an error was encountered while uploading dSYM to the server" 1
     fi
 else
-    exitOperation "Please select 'Debug information format' to 'DWARF with DSYM File' under Target Build Settings" 0
+    exitOperation "Please select 'Debug information format' to 'DWARF with DSYM File' under Target Build Settings" 1
 fi
 
 else
     
-    CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}")"
-    while ([ ! -f "$CM_ZA_INFOPLIST_FILE" ])
+    CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}" -not -path '*/.*' | head -1)"
+    while ([ ! -f "${CM_ZA_INFOPLIST_FILE}" ])
     do
-      CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}")"
-    echo "Waiting for the file to be copied ${CM_ZA_INFOPLIST_FILE}"
+      CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}" -not -path '*/.*' | head -1)"
+    echo "Waiting for the file to be copied at line number 311 ${CM_ZA_INFOPLIST_FILE}"
     sleep 1;
     done
       
+    echo "Data from target to source - skip upload dsym : ${CM_ZA_INFOPLIST_FILE}"
     echo $(/usr/libexec/PlistBuddy -c "Delete :APP_VERSION_META" "${ZA_INFOPLIST_FILE}")
     echo $(/usr/libexec/PlistBuddy -c "Delete :EVENTS_INFO" "${ZA_INFOPLIST_FILE}")
     echo $(/usr/libexec/PlistBuddy -c "Delete :API_INFO" "${ZA_INFOPLIST_FILE}")
+    echo $(/usr/libexec/PlistBuddy -c "Delete :LAST_MODIFIED" "${ZA_INFOPLIST_FILE}")
 
     echo $(/usr/libexec/PlistBuddy -c "Delete :AP_INFOPLIST_FILE" "${AP_INFO_FILE_NAME}")
     echo $(/usr/libexec/PlistBuddy -c "Delete :AP_APP_GROUP_IDENTIFIER" "${AP_INFO_FILE_NAME}")
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -13,7 +13,7 @@ ZA_INFOPLIST_FILE="apptics-config.plist"
 UUIDGEN="$(uuidgen)"
 ZA_VERSION_META_FILE_NAME="$UUIDGEN-apptics-version-meta.json"
 ZA_META_FILE_NAME="$UUIDGEN-apptics-meta"
-
+SYNC_TYPE="plist"
 HELP=0
 
 AP_INFO_FILE_NAME="$PRODUCT_SETTINGS_PATH" #INFOPLIST_FILE
@@ -21,13 +21,7 @@ CM_AP_INFO_FILE_NAME="$TARGET_BUILD_DIR/$INFOPLIST_PATH"
 
 #Apple script alert before dSYM upload
 function error_prompt() {
-osascript <<EOT
-tell app "System Events"
-
-button returned of (display alert "$1" message "$2" buttons {"Ok"} default button 1 as critical giving up after 10)
-
-end tell
-EOT
+echo "$1: $2"
 }
 
 eval "${GCC_PREPROCESSOR_DEFINITIONS}"
@@ -48,6 +42,9 @@ AP_APP_GROUP_IDENTIFIER="${1#*=}"
 ;;
 --log-file-path=*)
 LOG_FILE_PATH="${1#*=}"
+;;
+--sync-type=*)
+SYNC_TYPE="${1#*=}"
 ;;
 *)
 printf "**********************************\n"
@@ -173,11 +170,12 @@ API_KEY=$(/usr/libexec/PlistBuddy -c 'Print API_KEY' "${ZA_INFOPLIST_FILE}")
 fi
 
 if [ ! "${API_KEY}" ]; then
-value=$(error_prompt "Missing API_KEY" "Please check if the ${ZA_INFO_FILE_NAME} file is up to date?")
+value=$(error_prompt "Error" "Missing API_KEY, please check if the ${ZA_INFO_FILE_NAME} file is up to date?")
+exit 1
 fi
 
 if [ -z "${APPTICS_SDK_ID}" ]; then
-value=$(error_prompt "Missing APPTICS_SDK_ID, check the sdk_info file")
+value=$(error_prompt "Error" "Missing APPTICS_SDK_ID, check the sdk_info file")
 exit 1
 fi
 
@@ -214,7 +212,7 @@ eval BUNDLE_SHORT_VERSION="$(echo "$BUNDLE_SHORT_VERSION")"
 fi
 fi
 
-CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}")"
+CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}" -not -path '*/.*' | head -1)"
 
 if [ -f "${CM_ZA_INFOPLIST_FILE}" ]; then
 echo "Merging metadata from target to source"
@@ -252,7 +250,7 @@ API_INFO=$(/usr/libexec/PlistBuddy -c 'Print API_INFO' "${ZA_INFOPLIST_FILE}" 2>
 if [ "${SERVER_URL}" ]; then
 URL_ENDPOINT="${SERVER_URL}/sdk/api/apptics/v1/app/addversion"
 else
-value=$(error_prompt "Missing SERVER_URL" "Please check if the ${ZA_INFO_FILE_NAME} file is up to date?")
+value=$(error_prompt "Error" "Missing SERVER_URL, please check if the ${ZA_INFO_FILE_NAME} file is up to date?")
 exit 1
 fi
 
@@ -295,14 +293,21 @@ if [ "${APPTICS_SDK_ID}" != "${ZA_APPTICS_SDK_ID}" ] || [ "${BUNDLE_VERSION}" !=
   echo "${URL_ENDPOINT}?${REG_APP_VERSION_PARAMS} --write-out %{http_code} --silent -o "${reg_app_out_file}" -H "zak: ${API_KEY}" -X POST"
   
   if [ $STATUS -eq 200 ]; then
-  echo "Data downloaded"
+  echo "Info: Data downloaded"
   
   echo "$(command dirname -- "${0}")/apptics_utils.rb" -e "AppticsBot.main '${reg_app_out_file}'"
-  $(ruby -r "$(command dirname -- "${0}")/apptics_utils.rb" -e "AppticsBot.main '${reg_app_out_file}'")
-  
+  value=$(ruby -r "$(command dirname -- "${0}")/apptics_utils.rb" -e "AppticsBot.main '${reg_app_out_file}'")
+    
+    if [[ "$value" =~ ^error:* ]]; then
+        echo $value
+        exit 1
+    fi
+    
+    $value
+      
   response=$(ruby -rjson -e 'j = JSON.parse(File.read("'${reg_app_out_file}'")); puts j["result"]')
   if [ "$response" != "success" ]; then
-    echo "Error while regestering app version : $(cat "${reg_app_out_file}")"
+    echo "error: Problem while regestering app version : $(cat "${reg_app_out_file}")"
     rm "${reg_app_out_file}"
     exit 1
   else
@@ -372,6 +377,10 @@ fi
 
 URL_ENDPOINT="${SERVER_URL}/sdk/api/apptics/v1/engagement/getinfo?${params}"
 
+if [ "${SYNC_TYPE}" == "plist" ]; then
+URL_ENDPOINT="${SERVER_URL}/sdk/api/apptics/v1/engagement/getplist?${params}"
+fi
+
 #echo $(rm -v /tmp/"${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.json")
 
 STATUS=$(curl "${URL_ENDPOINT}" -v --write-out %{http_code} --silent -o "/tmp/${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.json" -H "zak: ${API_KEY}" -X POST --connect-timeout 60 --max-time 900 --retry 2 --retry-delay 5)
@@ -382,13 +391,21 @@ echo "ENGAGEMENT RESULT STATUS ${STATUS}"
 if [ $STATUS -eq 200 ]; then
 echo "Downloaded the data from Apptics"
 
-echo $(ruby -r "$(command dirname -- "${0}")/apptics_helper.rb" -e "AppticsEventsParser.main '${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}'")
+value=$(ruby -r "$(command dirname -- "${0}")/apptics_helper.rb" -e "AppticsEventsParser.main '${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}'")
+    
+    if [[ "$value" =~ ^error:* ]]; then
+        exit 1
+    fi
+    
+    echo $value
+        
 echo "AppticsEventsParser.main '${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}'"
 
 else
-echo "$STATUS Error occured ($?)"
+echo "error: response status : $STATUS, ($?)"
 exit 1
 fi
+
 /usr/libexec/PlistBuddy -c "Merge /tmp/${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.plist" "${ZA_INFOPLIST_FILE}"
 echo $(rm -v /tmp/"${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.json")
 echo $(rm -v /tmp/"${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.plist")
@@ -426,9 +443,9 @@ if [[ " ${SKIP_PROMPT_CONFIGURATIONS[@]} " =~ " ${CONFIGURATION} " ]]; then
   printf "*********************************************************************************************\n"
   printf "* Uploading dSYM for '${CONFIGURATION}' configuration, check $LOGNAME for more details *\n"
   printf "*********************************************************************************************\n"
-  sh "${COMMAND_PATH}" --skip-prompt=1 --upload-dsym=1 --process-type=0 >> $LOGNAME 2>&1 &
+  sh "${COMMAND_PATH}" --skip-prompt --upload-dsym --process-in-background >> $LOGNAME 2>&1 &
 else
-  sh "${COMMAND_PATH}" --skip-prompt=1 --upload-dsym=0 --process-type=0 >> $LOGNAME 2>&1 &
+  sh "${COMMAND_PATH}" --skip-prompt --process-in-background >> $LOGNAME 2>&1 &
   printf "****************************************************\n"
   printf "* Skipped dSYMs upload for '${CONFIGURATION}' configuration, check $LOGNAME for more details *\n"
   printf "****************************************************\n"
