Updating 1.1.1a with some fixes

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -10,10 +10,10 @@ DIR="$(command dirname -- "${0}")"
 source "${DIR}/sdk_info"
 
 ZA_INFOPLIST_FILE="apptics-config.plist"
-ZA_META_FILE_NAME="$(uuidgen)-apptics.json"
-projectname="."
-projectfilepath=""
-PREFIX="AP"
+UUIDGEN="$(uuidgen)"
+ZA_VERSION_META_FILE_NAME="$UUIDGEN-apptics-version-meta.json"
+ZA_META_FILE_NAME="$UUIDGEN-apptics-meta"
+
 HELP=0
 
 AP_INFO_FILE_NAME="$PRODUCT_SETTINGS_PATH" #INFOPLIST_FILE
@@ -42,7 +42,6 @@ SKIP_PROMPT_FOR="${1#*=}"
 ;;
 --config-file-path=*)
 ZA_INFOPLIST_FILE="${1#*=}"
-ZA_INFO_FILE_NAME=$(basename "/$ZA_INFOPLIST_FILE")
 ;;
 --app-group-identifier=*)
 AP_APP_GROUP_IDENTIFIER="${1#*=}"
@@ -57,7 +56,9 @@ esac
 shift
 done
 
-export ZA_INFOPLIST_FILE_PATH=$ZA_INFOPLIST_FILE
+ZA_INFO_FILE_NAME=$(basename "/$ZA_INFOPLIST_FILE")
+
+export ZA_INFO_FILE_NAME=$ZA_INFO_FILE_NAME
 
 if [ $HELP -eq 1 ];then
 echo "Options:\n"
@@ -68,7 +69,7 @@ echo "    --help                                Show help banner of specified co
 exit 1
 fi
 
-function plistManipulation() {
+function update_main_info_plist() {
 VALUE=$2
 KEY=$1
 
@@ -117,13 +118,13 @@ fi
 }
 
 if [ "${ZA_INFOPLIST_FILE}" ]; then
-plistManipulation "AP_INFOPLIST_FILE" "${ZA_INFOPLIST_FILE}"
+update_main_info_plist "AP_INFOPLIST_FILE" "${ZA_INFOPLIST_FILE}"
 else
 deleteItemFromPlist "AP_INFOPLIST_FILE"
 fi
 
 if [ "${AP_APP_GROUP_IDENTIFIER}" ]; then
-plistManipulation "AP_APP_GROUP_IDENTIFIER" "${AP_APP_GROUP_IDENTIFIER}"
+update_main_info_plist "AP_APP_GROUP_IDENTIFIER" "${AP_APP_GROUP_IDENTIFIER}"
 else
 deleteItemFromPlist "AP_APP_GROUP_IDENTIFIER"
 fi
@@ -151,7 +152,9 @@ PLATFORM="watchOS"
 APPTICS_SDK_ID=$WATCHOS_SDK_ID
 fi
 
-ZA_INFOPLIST_FILE=${SRCROOT}/${ZA_INFOPLIST_FILE}
+ZA_INFOPLIST_FILE="$(find "${SRCROOT}" -name "${ZA_INFO_FILE_NAME}" | head -1)"
+#${SRCROOT}/${ZA_INFOPLIST_FILE}
+echo "${ZA_INFOPLIST_FILE}"
 
 if [ ! -f "${ZA_INFOPLIST_FILE}" ]; then
 echo "regappversion : Please check if the ${ZA_INFO_FILE_NAME} is in your projects' root dir, or else provide the proper path by passing value to the param '--config-file-path'"
@@ -208,6 +211,18 @@ eval BUNDLE_SHORT_VERSION="$(echo "$BUNDLE_SHORT_VERSION")"
 fi
 fi
 
+CM_ZA_INFOPLIST_FILE="$(find "${TARGET_BUILD_DIR}" -name "${ZA_INFO_FILE_NAME}")"
+
+if [ -f "${CM_ZA_INFOPLIST_FILE}" ]; then
+echo "Merging metadata from target to source"
+/usr/libexec/PlistBuddy -c "Merge ${CM_ZA_INFOPLIST_FILE}" "${ZA_INFOPLIST_FILE}"
+rm "${CM_ZA_INFOPLIST_FILE}"
+fi
+
+mkdir "/tmp/${PRODUCT_BUNDLE_IDENTIFIER}"
+  
+echo "adding app_version_meta to main file for upload api\n$ZA_INFOPLIST_FILE \n $CM_ZA_INFOPLIST_FILE"
+
 APP_VERSION_ID=$(/usr/libexec/PlistBuddy -c 'Print APP_VERSION_META:APP_VERSION_ID' "${ZA_INFOPLIST_FILE}" 2>/dev/null || printf "")
   
 AAID=$(/usr/libexec/PlistBuddy -c 'Print APP_VERSION_META:AAID' "${ZA_INFOPLIST_FILE}" 2>/dev/null || printf "")
@@ -225,6 +240,11 @@ ZA_BUNDLE_SHORT_VERSION=$(/usr/libexec/PlistBuddy -c 'Print APP_VERSION_META:BUN
 ZA_APPTICS_SDK_ID=$(/usr/libexec/PlistBuddy -c 'Print APP_VERSION_META:APPTICS_SDK_ID' "${ZA_INFOPLIST_FILE}" 2>/dev/null || printf "")
 
 SERVER_URL=$(/usr/libexec/PlistBuddy -c 'Print SERVER_URL' "${ZA_INFOPLIST_FILE}")
+  
+EVENTS_INFO=$(/usr/libexec/PlistBuddy -c 'Print EVENTS_INFO' "${ZA_INFOPLIST_FILE}" 2>/dev/null || printf "")
+
+API_INFO=$(/usr/libexec/PlistBuddy -c 'Print API_INFO' "${ZA_INFOPLIST_FILE}" 2>/dev/null || printf "")
+
 
 if [ "${SERVER_URL}" ]; then
 URL_ENDPOINT="${SERVER_URL}/sdk/api/apptics/v1/app/addversion"
@@ -233,7 +253,7 @@ value=$(error_prompt "Missing SERVER_URL" "Please check if the ${ZA_INFO_FILE_NA
 exit 1
 fi
 
-printValueForKey(){
+value_for_key(){
 
 key=$1
 
@@ -241,7 +261,7 @@ echo "$key : $(/usr/libexec/PlistBuddy -c "Print APP_VERSION_META:$key" "${ZA_IN
 
 }
 
-checkAndUpdate(){
+check_and_update(){
 
 key=$1
 value=$2
@@ -249,7 +269,7 @@ value=$2
 echo "$key : $value"
 
 ID=$(/usr/libexec/PlistBuddy -c "Print APP_VERSION_META:$key" "${ZA_INFOPLIST_FILE}" 2>/dev/null || printf "null")
-echo "ID : ${ID}"
+echo "check and update : ${key}, ${ID}"
 if [ "${ID}" == "null" ]; then
 $(/usr/libexec/PlistBuddy -c "Add :APP_VERSION_META:$key string $value" "${ZA_INFOPLIST_FILE}")
 else
@@ -257,7 +277,7 @@ $(/usr/libexec/PlistBuddy -c "Set :APP_VERSION_META:$key $value" "${ZA_INFOPLIST
 fi
 }
 
-fetchAPP_VERSION_META() {
+prepare_build_apptics() {
 if [ "${PRODUCT_BUNDLE_IDENTIFIER}" != "${AP_BUNDLE_ID}" ]; then
     echo "Product bundle identifier '${PRODUCT_BUNDLE_IDENTIFIER}' doesn't match with the bundle identifier in '${ZA_INFO_FILE_NAME}' '${AP_BUNDLE_ID}'"
     exit 1
@@ -265,22 +285,25 @@ fi
 
 if [ "${APPTICS_SDK_ID}" != "${ZA_APPTICS_SDK_ID}" ] || [ "${BUNDLE_VERSION}" != "${ZA_BUNDLE_VERSION}" ] || [ "${BUNDLE_SHORT_VERSION}" != "${ZA_BUNDLE_SHORT_VERSION}" ] || [ "${APP_VERSION_ID}" == "" ] || [ "${AAID}" == "" ] || [ "${APID}" == "" ] || [ "${PLATFORM_ID}" == "" ] || [ "${APPTICS_SDK_ID}" == "" ] || [ "${RSAKEY}" == "" ]; then
   
-  out_file="/tmp/${ZA_META_FILE_NAME}"
+  reg_app_out_file="/tmp/${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_VERSION_META_FILE_NAME}"
   REG_APP_VERSION_PARAMS="platform=${OS}&identifier=${PRODUCT_BUNDLE_IDENTIFIER}&version=${BUNDLE_SHORT_VERSION}&appreleaseversion=${BUNDLE_VERSION}&frameworkid=${APPTICS_SDK_ID}&minosversion=${ZA_DEPLOYMENT_TARGET}"
-  STATUS=$(curl "${URL_ENDPOINT}?${REG_APP_VERSION_PARAMS}" -v --write-out %{http_code} --silent -o "${out_file}" -H "zak: ${API_KEY}" -X POST --connect-timeout 60 --max-time 900 --retry 2 --retry-delay 5)
+  STATUS=$(curl "${URL_ENDPOINT}?${REG_APP_VERSION_PARAMS}" -v --write-out %{http_code} --silent -o "${reg_app_out_file}" -H "zak: ${API_KEY}" -X POST --connect-timeout 60 --max-time 900 --retry 2 --retry-delay 5)
   
-  echo "${URL_ENDPOINT}?${REG_APP_VERSION_PARAMS} --write-out %{http_code} --silent -o "${out_file}" -H "zak: ${API_KEY}" -X POST"
+  echo "${URL_ENDPOINT}?${REG_APP_VERSION_PARAMS} --write-out %{http_code} --silent -o "${reg_app_out_file}" -H "zak: ${API_KEY}" -X POST"
   
   if [ $STATUS -eq 200 ]; then
   echo "Data downloaded"
   
-  echo "$(command dirname -- "${0}")/appticshelper.rb" -e "AppticsBot.main '${out_file}'"
-  $(ruby -r "$(command dirname -- "${0}")/appticshelper.rb" -e "AppticsBot.main '${out_file}'")
+  echo "$(command dirname -- "${0}")/apptics_utils.rb" -e "AppticsBot.main '${reg_app_out_file}'"
+  $(ruby -r "$(command dirname -- "${0}")/apptics_utils.rb" -e "AppticsBot.main '${reg_app_out_file}'")
   
-  response=$(ruby -rjson -e 'j = JSON.parse(File.read("'${out_file}'")); puts j["result"]')
+  response=$(ruby -rjson -e 'j = JSON.parse(File.read("'${reg_app_out_file}'")); puts j["result"]')
   if [ "$response" != "success" ]; then
-    echo "Error while regestering app version : $(cat "${out_file}")"
+    echo "Error while regestering app version : $(cat "${reg_app_out_file}")"
+    rm "${reg_app_out_file}"
     exit 1
+  else
+    rm "${reg_app_out_file}"
   fi
             
   if [ "$appversionid" == "" ] || [ "$appreleaseversionid" == "" ] || [ "$aaid" == "" ] || [ "$apid" == "" ] || [ "$mapid" == "" ] || [ "$rsakey" == "" ] || [ "$platformid" == "" ] || [ "$APPTICS_SDK_ID" == "" ]; then
@@ -293,40 +316,84 @@ if [ "${APPTICS_SDK_ID}" != "${ZA_APPTICS_SDK_ID}" ] || [ "${BUNDLE_VERSION}" !=
       echo "PLATFORM_ID" "$platformid"
       echo "BUNDLE_VERSION" "$BUNDLE_VERSION"
       echo "BUNDLE_SHORT_VERSION" "$BUNDLE_SHORT_VERSION"
-      echo "APPTICS_SDK_ID" "${APPTICS_SDK_ID}"    
+      echo "APPTICS_SDK_ID" "${APPTICS_SDK_ID}"
   exit 1;
   fi
-  checkAndUpdate "APP_VERSION_ID" "$appversionid"
-  checkAndUpdate "APP_RELEASE_VERSION_ID" "$appreleaseversionid"
-  checkAndUpdate "AAID" "$aaid"
-  checkAndUpdate "APID" "$apid"
-  checkAndUpdate "MAPID" "$mapid"
-  checkAndUpdate "RSAKEY" "$rsakey"
-  checkAndUpdate "PLATFORM_ID" "$platformid"
-  checkAndUpdate "BUNDLE_VERSION" "$BUNDLE_VERSION"
-  checkAndUpdate "BUNDLE_SHORT_VERSION" "$BUNDLE_SHORT_VERSION"
-  checkAndUpdate "APPTICS_SDK_ID" "${APPTICS_SDK_ID}"
+  check_and_update "APP_VERSION_ID" "$appversionid"
+  check_and_update "APP_RELEASE_VERSION_ID" "$appreleaseversionid"
+  check_and_update "AAID" "$aaid"
+  check_and_update "APID" "$apid"
+  check_and_update "MAPID" "$mapid"
+  check_and_update "RSAKEY" "$rsakey"
+  check_and_update "PLATFORM_ID" "$platformid"
+  check_and_update "BUNDLE_VERSION" "$BUNDLE_VERSION"
+  check_and_update "BUNDLE_SHORT_VERSION" "$BUNDLE_SHORT_VERSION"
+  check_and_update "APPTICS_SDK_ID" "${APPTICS_SDK_ID}"
+  echo "Data updated"
   
-    echo "Data updated"
   else
   echo "$STATUS Error occured ($?)"
   exit 1
   fi
 else
   echo "App version is already registered"
-  printValueForKey "APP_VERSION_ID"
-  printValueForKey "APP_RELEASE_VERSION_ID"
-  printValueForKey "AAID"
-  printValueForKey "APID"
-  printValueForKey "MAPID"
-  printValueForKey "RSAKEY"
-  printValueForKey "PLATFORM_ID"
-  printValueForKey "BUNDLE_VERSION"
-  printValueForKey "BUNDLE_SHORT_VERSION"
-  printValueForKey "APPTICS_SDK_ID"
+  value_for_key "APP_VERSION_ID"
+  value_for_key "APP_RELEASE_VERSION_ID"
+  value_for_key "AAID"
+  value_for_key "APID"
+  value_for_key "MAPID"
+  value_for_key "RSAKEY"
+  value_for_key "PLATFORM_ID"
+  value_for_key "BUNDLE_VERSION"
+  value_for_key "BUNDLE_SHORT_VERSION"
+  value_for_key "APPTICS_SDK_ID"
   echo "App version : ${BUNDLE_VERSION}"
   echo "App short version : ${BUNDLE_SHORT_VERSION}"
 fi
+
+#####################
+
+echo "EVENTS_TRACKING_ID : ${EVENTS_TRACKING_ID}"
+echo "API_TRACKING_ID : ${API_TRACKING_ID}"
+
+if [ "${EVENTS_INFO}" == "" ] || [ "${API_INFO}" == "" ];then
+params="moduleids"
+
+if [ "${EVENTS_TRACKING_ID}" ]; then
+params="${params}=5,"
+fi
+
+if [ "${API_TRACKING_ID}" ]; then
+params="${params}6,"
+fi
+
+URL_ENDPOINT="${SERVER_URL}/sdk/api/apptics/v1/engagement/getinfo?${params}"
+
+#echo $(rm -v /tmp/"${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.json")
+
+STATUS=$(curl "${URL_ENDPOINT}" -v --write-out %{http_code} --silent -o "/tmp/${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.json" -H "zak: ${API_KEY}" -X POST --connect-timeout 60 --max-time 900 --retry 2 --retry-delay 5)
+echo "${URL_ENDPOINT}" --write-out %{http_code} --silent -o "/tmp/${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.json" -H "zak: ${API_KEY}"
+
+echo "ENGAGEMENT RESULT STATUS ${STATUS}"
+
+if [ $STATUS -eq 200 ]; then
+echo "Downloaded the data from Apptics"
+
+echo $(ruby -r "$(command dirname -- "${0}")/apptics_helper.rb" -e "AppticsEventsParser.main '${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}'")
+echo "AppticsEventsParser.main '${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}'"
+
+else
+echo "$STATUS Error occured ($?)"
+exit 1
+fi
+/usr/libexec/PlistBuddy -c "Merge /tmp/${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.plist" "${ZA_INFOPLIST_FILE}"
+echo $(rm -v /tmp/"${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.json")
+echo $(rm -v /tmp/"${PRODUCT_BUNDLE_IDENTIFIER}/${ZA_META_FILE_NAME}.plist")
+fi
+
+
+
+#####################
 
 DIR="$(command dirname -- "${0}")"
 
@@ -334,12 +401,9 @@ COMMAND_PATH="$DIR/dsym_upload"
 
 IFS=', ' read -r -a SKIP_PROMPT_CONFIGURATIONS <<< "${SKIP_PROMPT_FOR}"
 
-if [[ " ${SKIP_PROMPT_CONFIGURATIONS[@]} " =~ " ${CONFIGURATION} " ]]; then
-  LOGNAME="/tmp/apptics-output.txt"
-  MAXSIZE=100000
- 
- rm -rvf "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
- 
+LOGNAME="/tmp/${PRODUCT_BUNDLE_IDENTIFIER}/${UUIDGEN}-apptics-output.txt"
+MAXSIZE=100000
+
   if [ -f "${LOGNAME}" ]; then
     LOGNAME_SIZE=$(ls -l $LOGNAME | awk '{print $5}')
     if [ $LOGNAME_SIZE -ge $MAXSIZE ];
@@ -348,18 +412,23 @@ if [[ " ${SKIP_PROMPT_CONFIGURATIONS[@]} " =~ " ${CONFIGURATION} " ]]; then
         rm $LOGNAME
     fi
   fi
-
+  
+if [[ " ${SKIP_PROMPT_CONFIGURATIONS[@]} " =~ " ${CONFIGURATION} " ]]; then
+ 
+# rm -rvf "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
+  
   printf "*********************************************************************************************\n"
   printf "* Uploading dSYM for '${CONFIGURATION}' configuration, check $LOGNAME for more details *\n"
   printf "*********************************************************************************************\n"
-  sh "${COMMAND_PATH}" --skip-prompt=1 >> $LOGNAME 2>&1 &
+  sh "${COMMAND_PATH}" --skip-prompt=1 --upload-dsym=1 >> $LOGNAME 2>&1 &
 else
+  sh "${COMMAND_PATH}" --skip-prompt=1 --upload-dsym=0 >> $LOGNAME 2>&1 &
   printf "****************************************************\n"
-  printf "* Skipped dSYMs upload for '${CONFIGURATION}' configuration *\n"
+  printf "* Skipped dSYMs upload for '${CONFIGURATION}' configuration, check $LOGNAME for more details *\n"
   printf "****************************************************\n"
 fi
 
 }
 
-fetchAPP_VERSION_META $1
+prepare_build_apptics $1
 
